# Generated by Django 3.0.8 on 2020-07-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200718_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='isMVP',
            field=models.BooleanField(default=False),
        ),
    ]
